site_name: MSK BLAZE FHIR DEVELOPER DOCUMENTATION
theme:
  name: material
  logo: assets/logo-arrow-sans-medium-black.svg
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2022 MSKCC
nav:
  - Home: index.md
  - Authentication: authentication.md
  - Pagination: pagination.md
  - Resources:
    - Labs: resources/labs.md
    - Vitals: resources/vitals.md
  - "Coming Soon":
    - Demographics: coming-soon/demographics.md
    - "Adverse Events": coming-soon/adverseEvents.md
    - Medications: coming-soon/medications.md
  - Blog: blog.md
  - Release Notes: releasenotes.md