site_name: MSK BLAZE FHIR DEVELOPER DOCUMENTATION
theme:
  name: material
  logo: assets/logo-arrow-sans-medium-black.svg
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2022 MSKCC
extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/memorialsloankettering/
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/memorialsloankettering
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MSKCancerCenter
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/mskcc
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/memorial-sloan-kettering-cancer-center/mycompany/


nav:
  - Home: index.md
  - Authentication: authentication.md
  - Searching: searching.md
  - Pagination: pagination.md
  - Available Resources:
    - "Adverse Events": resources/adverse-events.md
    - Demographics: resources/demographics.md
    - Labs: resources/labs.md
    - Vitals: resources/vitals.md
  - "Coming Soon":
    - Medications: coming-soon/medications.md
    - RECIST: coming-soon/recist.md
  - Identifiers: identifiers.md
  - Releases: releases.md
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

